export const character=[
    {
        id: 1,
        image: "https://cdn.runescape.com/assets/img/external/oldschool/2024/newsposts/2024-01-15/WinterSummit-Thumbnail.jpg",
        category:"Heroic Champions:",
        name: "Sir Turael",
        description:"Everything you need to know about the 2024 Winter Summit in one handy post! Read More...",
      },
    {
        id: 2,
        image: "https://cdn.runescape.com/assets/img/external/oldschool/2024/newsposts/2024-01-15/WinterSummit-Thumbnail.jpg",
        category:"Heroic Champions:",
        name: "Griselda",
        description:"A wise sorceress residing in Ape Atoll, known for her powerful magic and cryptic wisdom.",
      },
    {
        id: 3,
        image: "https://cdn.runescape.com/assets/img/external/oldschool/2024/newsposts/2024-01-15/WinterSummit-Thumbnail.jpg",
        category:"Heroic Champions:",
        name: "TzHaar-Ket-Zog",
        description:"A fierce TzHaar general leading the TzHaar resistance against the Kalphite Queens.",
      },
    {
        id: 4,
        image: "https://lh3.googleusercontent.com/bip/AAewDPz7YnlLqScwYkWU79_0OJWDT8wNjg3ai5j2zLQviGmPIA8vFPDJ4oaaoeV1PVbh2thjP1-htNwMMXGziFc1ln40A8O1QE3sQk5Bxz-OfXCiPE6TeQ_gTlFsE01raRpZz4w39vilWE3KbZW8cPCSZ8H0gMjj=w250-h200-p",
        category:"Mischievous Villains:",
        name: "Skotizo:",
        description:"A monstrous demon with glowing red eyes and razor-sharp claws, emerging from a shadowy portal.",
      },
    {
        id: 5,
        image: "https://lh3.googleusercontent.com/bip/AAewDPyfX6iBEZnLqcOAdz2M_W1L2JWf_2A9O8cJP5fU-mH01aT6H6InzYZnlvfSX5TtzqZoc0g2cTM67LQPhPNNtwhEmFdgRSH5vX1v14by8wVW7R7n7Mw2js99HHjbpFuLqjNT7ay6IQrfepoxZehGc8ul9ZLOg6hPXigH63vbvTRz8VhpXzNZ2JxsHfJ2xOpSIQpyep8=w250-h200-p",
        category:"Mischievous Villains:",
        name: "Zulrah:",
        description:"A serpentine creature with vibrant scales and deadly fangs, slithering through its flooded lair.",
      },
    {
        id: 6,
        image: "https://lh3.googleusercontent.com/bip/AAewDPwliWFvSuqKJ1lWmsUs6_O7mI7hiQxwCoBIz9m969evckMPQk0pCTFsZWRfYrG8d1GHqlchqE8Adks1FcP3DlwP--NIE8lPFI0hoGaEj5ZqMnLV0G5-PUCOj02lo5H8wGD9KB_HROFU6bd48kD_h8R4c_o98osqXWUa5xqM-Nf3ubgYrvKOgy69v6foBXyEyZwpbwfSROYjxJQ5wW_h36TBE2pqJg=w250-h200-p",
        category:"Mischievous Villains:",
        name: "The Dragon Slayer",
        description:"A shrouded figure shrouded in mystery, wielding a glowing dagger and radiating an ominous aura.",
      },
    {
        id: 7,
        image: "https://lh3.googleusercontent.com/bip/AAewDPzmUmn43WOdhMCQe1UHiZVwPH-7hzigzm2AxLM9IG6s6nmJUYF8wzxmxKirJoRiuMyDeS310YmdOs1LxIW--ycLxORcT6AwLRW5lh9IIAW_5hVHezF2kE8Uos3PxAebavsf7BUfsiIPICdqtORAP0AsBflTrhkD1CsYCKAGM0k=w250-h200-p",
        category:"Helpful Guides:",
        name: "Wise Old Man: ",
        description:"A friendly wizard with a long white beard and twinkling eyes, standing outside his cozy cottage.",
      },
    {
        id: 8,
        image: "https://lh3.googleusercontent.com/bip/AAewDPysfy2_HHKnl6lsNxbSSIWqFHfdxJzWU6CqpycLm1ucxSWJtm_qqYu9EyhkOEy2M3vjwGVyv9qSphaL9BDhtxP1bqkg_HiVaClFMjSlKywQiPCir5CsluQS04kW=w250-h200-p",
        category:"Helpful Guides:",
        name: "Oziach: ",
        description:"A dwarven engineer with bushy eyebrows and a tinkering toolbelt, inspecting a complex machine.",
      },
    {
        id: 9,
        image: "https://lh3.googleusercontent.com/bip/AAewDPwliWFvSuqKJ1lWmsUs6_O7mI7hiQxwCoBIz9m969evckMPQk0pCTFsZWRfYrG8d1GHqlchqE8Adks1FcP3DlwP--NIE8lPFI0hoGaEj5ZqMnLV0G5-PUCOj02lo5H8wGD9KB_HROFU6bd48kD_h8R4c_o98osqXWUa5xqM-Nf3ubgYrvKOgy69v6foBXyEyZwpbwfSROYjxJQ5wW_h36TBE2pqJg=w250-h200-p",
        category:"Helpful Guides:",
        name: "Dorran:",
        description:"A resourceful gnome adventurer with a mischievous grin and a backpack full of gadgets, exploring a hidden cave.",
      },
    {
        id: 10,
        image: "https://lh3.googleusercontent.com/bip/AAewDPyXCbyWO11ZVidR1OlBKn9asRBVrZLesaXPcO0Mr-1FIduL8oEh6dhQ9l2pQiY-CsymnIr-8JTIOVv3YHTzH-XBGveLdbxFjOx-jwVeNRHyf-I4LWbLXObqC6U0-i5_ADntwnCs6PsMwfC7DH9IiRbncwnTvJqa_YKh9rNC24vSb7SqAHg=w250-h200-p",
        category:"HLegendary Beasts:",
        name: "The Corporeal Beast:",
        description:"A colossal serpent coiled around a burning altar, composed of swirling undead energy. ",
      },
    {
        id: 11,
        image: "https://lh3.googleusercontent.com/bip/AAewDPysfy2_HHKnl6lsNxbSSIWqFHfdxJzWU6CqpycLm1ucxSWJtm_qqYu9EyhkOEy2M3vjwGVyv9qSphaL9BDhtxP1bqkg_HiVaClFMjSlKywQiPCir5CsluQS04kW=w250-h200-p",
        category:"Legendary Beasts:",
        name: "Theatre of Blood's Guardians: ",
        description:"Seven monstrous creatures with unique appearances and deadly abilities, guarding the entrance to the theatre.",
      },
   
]